"""add stripe_checkout_session_id to orders

Revision ID: 6cd550893682
Revises: f5675eddcdf0
Create Date: 2026-08-10 14:23:05.676401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cd550893682'
down_revision: Union[str, Sequence[str], None] = 'f5675eddcdf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('stripe_checkout_session_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'stripe_checkout_session_id')
    # ### end Alembic commands ###
