"""add unique constraint on reviews user_id product_id

Revision ID: 7dcde36b30d6
Revises: 4c552db7ceb6
Create Date: 2026-09-09 16:34:58.761603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dcde36b30d6'
down_revision: Union[str, Sequence[str], None] = '4c552db7ceb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_review_user_product', 'reviews', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_review_user_product', 'reviews', type_='unique')
    # ### end Alembic commands ###
